task_groups:
    pattern:  /task-groups
    defaults: { _controller: TaskBufferBundle:TaskBuffer:taskGroups, offset: ~, limit: ~ }
    
task_group:
    pattern:  /task-group/{taskGroupId}
    defaults: { _controller: TaskBufferBundle:TaskBuffer:taskGroup, task_group_id: taskGroupId }

task_delete:
    pattern:  /task-delete/{taskId}
    defaults: { _controller: TaskBufferBundle:TaskBuffer:taskDelete, task_id: taskId }
    
task_group_delete:
    pattern:  /task-group-delete/{taskGroupId}
    defaults: { _controller: TaskBufferBundle:TaskBuffer:taskGroupDelete, task_group_id: taskGroupId }
    
task_delete_old:
    pattern:  /delete-old-tasks
    defaults: { _controller: TaskBufferBundle:TaskBuffer:deleteOldTasks}

task_pull:
    pattern:  /pull
    defaults: { _controller: TaskBufferBundle:TaskBuffer:pull, stop: ~, limit: ~ }
  